### ISSUE TITLE
Running elizabeth with launchd

### ISSUE THREAD

**Issue by b-woods** [pwaldhauer/elizabeth#20]
Not an issue, but seeking some advice.

I'd like to run elizabeth nightly on a mac using launchd via either Lingon or LaunchControl, but I'm struggling to make it work. I'm sure it's down to my inexperience, so any advice of how to configure to plist file, or where permissions etc might be getting in the way would be great.

Thanks!

**Comment by blueneogeo** [comment]
I also was unable to do this. Anyone have success making elizabeth run daily on a mac?

**Comment by b-woods** [comment]
Sadly I still don't have a solution to this, I've been running it manually each week. I'd love to find a solution to this as I imagine it is fairly simple - but just out of grasp of my knowledge/experience.

**Comment by pwaldhauer** [comment]
Maybe you could just use a cronjob? Closing this issue now.
